#!/usr/bin/env bash
# Useful aliases and functions
ce Green running .aliases

###########
# ALIASES #
###########
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

unalias which 2>/dev/null  # Stupid centos: https://superuser.com/q/115356311

# LS #
the_ls=$(which gls 2>/dev/null)
[[ -z "$the_ls" ]] && the_ls=$(which ls)
# gnu ls is `gls` on FreeBSD, if it exists just use that as per usual
uname -a | grep FreeBSD >/dev/null 2>&1 \
&& [[ "$the_ls" == "ls" ]] && alias ls="ls -G" \
|| alias ls="LC_COLLATE=C $the_ls --color --group-directories-first"
# ^^ ASCIIbetical! https://ubuntuforums.org/showthread.php?t=816753

# jones77's Unix alphabet:
alias gg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gs='cd ~/github/scripts; ls'
alias gv='cd ~/github/vagrants; ls'
alias ll="ls -latr"
alias pp="ps aux"
alias tt='tmux attach -d'
alias va="vagrant"
alias vp="vagrant"
alias vu="vim '+PluginInstall!' +qall"
alias vv='_vi'
#############
# FUNCTIONS #
#############
jj_vim_options="-X"
function _vi {
    # Auto-start Obsession sessions.  https://github.com/tpope/vim-obsession
    (( $# == 0 )) && [[ -f Session.vim ]] \
        && vim $jj_vim_options -S Session.vim \
        || vim $jj_vim_options "$@";
}
function hh {
    hostname
    uname -a
    lsb_release -a
}
function azify {
    # http://stackoverflow.com/a/23816607/469045
    echo "$@" | tr -dc '[:alnum:]' | tr '[:upper:]' '[:lower:]'
}
function pre_add_path {
    # pre_add_path & post_add_path: https://gist.github.com/morganp/964200
    [[ -s "$1" ]] && [[ ":$PATH:" != *":$1:"* ]] && PATH="$1:$PATH" || :
}
function post_add_path {
    [[ -s "$1" ]] && [[ ":$PATH:" != *":$1:"* ]] && PATH="$PATH:$1" || :
}
function unsafe_sshkeygen {
    ssh-keygen -t rsa -q -P ""
}
function trash {
    [[ ! -d "~/.trash" ]] && mkdir -p ~/.trash
    mv "$@" ~/.trash
}
