#!/usr/bin/env bash
ce Green running .aliases

alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias less="less -ir"  # Make search case-insensitive, use colors.

alias  b="bat"
alias bb="curl -Ss http://169.254.169.254/openstack/latest/meta_data.json | python -m json.tool"
alias  c="calc"
alias  f="fzf -m --no-height --preview 'bat {}'"
alias fx="ag '(TODO:|FIXME:)'"
alias fx0="_agd '(TODO:|FIXME:)' 0"
alias ga="git add"
alias gb="git branch -vv"
alias gc="git commit"
alias gcm="_gcm"  # git commit -m "$*"
alias gd="git diff"
alias gdc="git diff --cached"
alias gg="git log --graph --pretty=format:'%Cred%h%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%C(yellow)%d' --abbrev-commit"
alias gp='git pull'
alias gs='git status -s'
alias jr='cd ~/src/bitbucket/scratch && ls'
alias js='cd ~/src/bitbucket/scripts && ls'
alias jv='cd ~/src/bitbucket/vagrants && ls'
alias ll="ls -latr"
alias lz="ls -laShr"
alias pp="ps aux"
alias st="sed 's/\x1b\[[0-9;]*m//g'"  # strip color, https://superuser.com/a/380778
alias  t='_t'  # FIXME: Make this work again.
alias tt='tmux attach -d'
alias va="vagrant"
alias vc="vim '+PluginClean!' +qall"
alias vf='v $(f)'
alias vu="vim '+PluginInstall!' +qall"
alias  v='_vi'
alias vn='_vi _vi__RECREATE__ _vi__RECREATE__'  # Magic vars for a new session.
alias wf='python -m pyftpdlib -w'  # sudo pip install pyftpdlib
alias ws='python -m SimpleHTTPServer 8000'
######
# ls # Configure ASCIIbetical gnu ls using LC_COLLATE=C, if it exists
######
the_ls=$(type -P gls 2>/dev/null)           # Does gls (gnu ls) exist?
[[ -z "$the_ls" ]] && the_ls=$(type -P ls)  # If not, use default ls.
__uname_freebsd=$(uname -a | grep FreeBSD >/dev/null 2>&1)  # TODO: Use FreeBSD.
if [[ -n "$__uname_freebsd" ]] && [[ "$the_ls" == "ls" ]]
then
    # Non-gnu ls.
    ce Red "ls is ls -G"
    alias ls="ls -G"
else
    ce Yellow "ls is ASCIIbetical"
    alias ls="LC_COLLATE=C $the_ls --color --group-directories-first"
    # ^^ ASCIIbetical! https://ubuntuforums.org/showthread.php?t=816753
fi
#############
# Functions #
#############
function _agd() {  # _agd pattern depth
    pattern="$1"
    depth="$2"
    ag --depth "$depth" "$pattern"
}
function _gcm() {
    git commit -m"$*"
}
function _t() {
    (
        cd ~/src/github/scratch || return
        git pull -q
        [[ "$(git diff -- tasks/tasks | wc -l)" != "0" ]] \
            && git add -- tasks/tasks \
            && git commit -q --no-status -m "Task: $(date +%Y%m%d%H%M%S)" \
            && git push -q
    )
    python ~/src/github/t/t.py --task-dir ~/src/scratch/tasks --list tasks
}
jj_vim_options="-X"
function _vi {
    if (( $# == 0 )) && [[ -f Session.vim ]]
    then
        vim $jj_vim_options -S Session.vim
    elif [[ $1 == _vi__RECREATE__ && $2 == _vi__RECREATE__ ]]
    then
        shift 2
        true >Session.vim  # force create empty session
        vim $jj_vim_options -c Obsess -S Session.vim "$@"
    else
        vim $jj_vim_options "$@"
    fi
}
function hh {
    hostname
    uname -a
    lsb_release -a
}
function azify {
    # http://stackoverflow.com/a/23816607/469045
    echo "$@" | tr -dc '[:alpha:]' | tr '[:upper:]' '[:lower:]'
}
function pre_add_path {
    # pre_add_path & post_add_path: https://gist.github.com/morganp/964200
    if [[ -s "$1" ]]
    then
        [[ ":$PATH:" != *":$1:"* ]] && PATH="$1:$PATH"
    fi
}
function post_add_path {
    if [[ -s "$1" ]]
    then
        [[ ":$PATH:" != *":$1:"* ]] && PATH="$PATH:$1"
    fi
}
function unsafe_sshkeygen {
    if [[ -f ~/.ssh/id_rsa ]]
    then
        echo "Warning: ~/.ssh/id_rsa already exists, replace? [y/n]"
        read -r answer
        if [[ "$answer" != "y" ]]
        then
            echo "not replacing ~/.ssh/id_rsa"
            return 1
        fi
    fi
    ssh-keygen -t rsa -q -P ""
    echo "$HOME/.ssh/id_rsa.pub:"
    echo
    cat ~/.ssh/id_rsa.pub
}
function trash {
    [[ ! -d "$HOME/.trash" ]] && mkdir -p "$HOME/.trash"
    mv "$@" "$HOME/.trash"
}
function calc {
    echo "$@" | bc -l
}
[[ -f "${HOME}/.aliases.extra" ]] && source "${HOME}/.aliases.extra"
