#!/usr/bin/env bash
# requires source shelllib.sh
ce Green running .aliases
function _info() {
    ce Yellow "  $*"
}

alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias less="less -i"  # Make search case-insensitive

# Configure an ASCIIbetical gnu ls for any platforms.
the_ls=$(type -P gls 2>/dev/null)  # Use gls, gnu ls if it exists
[[ -z "$the_ls" ]] && the_ls=$(type -P ls)  # Otherwise default ls
# gnu ls is `gls` on FreeBSD, if it exists just use that as per usual
__uname=$(uname -a | grep FreeBSD >/dev/null 2>&1)
if [[ -n "$__uname" ]] && [[ "$the_ls" == "ls" ]]
then
    _info "ls is ls -G"
    alias ls="ls -G"  # MacOS
else
    _info "ls is ASCIIbetical"
    alias ls="LC_COLLATE=C $the_ls --color --group-directories-first"
    # ^^ ASCIIbetical! https://ubuntuforums.org/showthread.php?t=816753
fi

alias bb="curl -Ss http://169.254.169.254/openstack/latest/meta_data.json | python -m json.tool"
alias fx="ag '(TODO:|FIXME:)'"
alias fx0="ag --depth 0 '(TODO:|FIXME:)'"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gdc="git diff --cached"
alias gg="git log --graph --pretty=format:'%Cred%h%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%C(yellow)%d' --abbrev-commit"
alias gp='git pull'
alias gs='git st'
alias jr='cd ~/src/bitbucket/scratch && ls'
alias js='cd ~/src/bitbucket/scripts && ls'
alias jv='cd ~/src/bitbucket/vagrants && ls'
alias ll="ls -latr"
alias lz="ls -laShr"
alias pp="ps aux"
alias st="sed 's/\x1b\[[0-9;]*m//g'"  # strip color, https://superuser.com/a/380778
# TODO: Make this a function.
# TODO: Use bitbucket.
function t() {
    (
        cd ~/src/scratch || return
        git pull -q
        [[ "$(git diff -- tasks/tasks | wc -l)" != "0" ]] \
            && git add -- tasks/tasks \
            && git commit -q --no-status -m "Task: $(date +%Y%m%d%H%M%S)" \
            && git push -q
    )
    python ~/src/github/t/t.py --task-dir ~/src/scratch/tasks --list tasks
}
alias tt='tmux attach -d'
alias va="vagrant"
alias vp="vagrant"
alias vu="vim '+PluginInstall!' +qall"
alias  v='_vi'
alias wf='python -m pyftpdlib -w'  # sudo pip install pyftpdlib
alias ws='python -m SimpleHTTPServer 8000'
#############
# FUNCTIONS #
#############
jj_vim_options="-X"
function _vi {
    if (( $# == 0 )) && [[ -f "Session.vim" ]]
    then
        vim $jj_vim_options -S Session.vim
    else
        vim $jj_vim_options "$@"
    fi
}
function hh {
    hostname
    uname -a
    lsb_release -a
}
function azify {
    # http://stackoverflow.com/a/23816607/469045
    echo "$@" | tr -dc '[:alpha:]' | tr '[:upper:]' '[:lower:]'
}
function pre_add_path {
    # pre_add_path & post_add_path: https://gist.github.com/morganp/964200
    if [[ -s "$1" ]]
    then
        [[ ":$PATH:" != *":$1:"* ]] && PATH="$1:$PATH"
    fi
}
function post_add_path {
    if [[ -s "$1" ]]
    then
        [[ ":$PATH:" != *":$1:"* ]] && PATH="$PATH:$1"
    fi
}
function unsafe_sshkeygen {
    if [[ -f ~/.ssh/id_rsa ]]
    then
        echo "Warning: ~/.ssh/id_rsa already exists, replace? [y/n]"
        read -r answer
        if [[ "$answer" != "y" ]]
        then
            echo "not replacing ~/.ssh/id_rsa"
            return 1
        fi
    fi
    ssh-keygen -t rsa -q -P ""
    echo "$HOME/.ssh/id_rsa.pub:"
    echo
    cat ~/.ssh/id_rsa.pub
}
function trash {
    [[ ! -d "$HOME/.trash" ]] && mkdir -p "$HOME/.trash"
    mv "$@" "$HOME/.trash"
}
function calc {
    echo "$@" | bc -l
}
[[ -f "${HOME}/.aliases.extra" ]] && source "${HOME}/.aliases.extra"
