#!/usr/bin/env bash
# Useful aliases and functions
ce Green running .aliases

###########
# ALIASES #
###########
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

unalias which 2>/dev/null  # Stupid centos: https://superuser.com/q/115356311

# LS #
the_ls=$(which gls 2>/dev/null)
[[ -z "$the_ls" ]] && the_ls=$(which ls)
# gnu ls is `gls` on FreeBSD, if it exists just use that as per usual
uname -a | grep FreeBSD >/dev/null 2>&1 \
  && [[ "$the_ls" == "ls" ]] && alias ls="ls -G" \
  || alias ls="LC_COLLATE=C $the_ls --color --group-directories-first"
# ^^ ASCIIbetical! https://ubuntuforums.org/showthread.php?t=816753

alias bb="curl -Ss http://169.254.169.254/openstack/latest/meta_data.json | python -m json.tool"
#alias f='find' or alias f='fortune', see .profile.extra
alias  g='grep'
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gp='git pull'
alias gs='git st'
alias jr='cd ~/src/scratch; ls'
alias js='cd ~/src/bitbucket/scripts; ls'
alias jv='cd ~/src/bitbucket/vagrants; ls'
alias  l="ls -latr"
alias lz="ls -laShr"
alias pp="ps aux"
alias st="sed 's/\x1b\[[0-9;]*m//g'"  # strip color, https://superuser.com/a/380778
alias  t='(
    cd ~/src/scratch
    git pull -q
    [[ "$(git diff -- tasks/tasks | wc -l)" != "0" ]] \
        && git add -- tasks/tasks \
        && git commit -q --no-status -m "Task: $(date +%Y%m%d%H%M%S)" \
        && git push -q
); python ~/src/github/t/t.py --task-dir ~/src/scratch/tasks --list tasks'
alias tt='tmux attach -d'
alias va="vagrant"
alias vp="vagrant"
alias vu="vim '+PluginInstall!' +qall"
alias vv='_vi'
alias ws='python -m SimpleHTTPServer 8000'
#############
# FUNCTIONS #
#############
jj_vim_options="-X"
function _vi {
    if (( $# == 0 )) && [[ -f "Session.vim" ]]
    then
        vim $jj_vim_options -S Session.vim
    else
        vim $jj_vim_options "$@"
    fi
}
function hh {
    hostname
    uname -a
    lsb_release -a
}
function azify {
    # http://stackoverflow.com/a/23816607/469045
    echo "$@" | tr -dc '[:alnum:]' | tr '[:upper:]' '[:lower:]'
}
function pre_add_path {
    # pre_add_path & post_add_path: https://gist.github.com/morganp/964200
    if [[ -s "$1" ]]
    then
        [[ ":$PATH:" != *":$1:"* ]] && PATH="$1:$PATH"
    fi
}
function post_add_path {
    if [[ -s "$1" ]]
    then
        [[ ":$PATH:" != *":$1:"* ]] && PATH="$PATH:$1"
    fi
}
function unsafe_sshkeygen {
    if [[ -f ~/.ssh/id_rsa ]]
    then
        echo "Warning: ~/.ssh/id_rsa already exists, replace? [y/n]"
        read answer
        if [[ "$answer" != "y" ]]
        then
            echo "not replacing ~/.ssh/id_rsa"
            return 1
        fi
    fi
    ssh-keygen -t rsa -q -P ""
    echo "~/.ssh/id_rsa.pub:"
    echo
    cat ~/.ssh/id_rsa.pub
}
function trash {
    [[ ! -d "$HOME/.trash" ]] && mkdir -p "$HOME/.trash"
    mv "$@" "$HOME/.trash"
}
[[ -f "${HOME}/.aliases.extra" ]] && source "${HOME}/.aliases.extra"
